### ISSUE TITLE
Migrate environments to vault_config (v2.8.0)

### ISSUE THREAD

**Issue by venimus** [aeternity/infrastructure#441]
- [x] uat https://github.com/aeternity/terraform-aws-testnet/pull/14
- [x] api_uat https://github.com/aeternity/terraform-aws-testnet-api/pull/13
- [x] uat_mon https://github.com/aeternity/terraform-aws-testnet/pull/14
- [x] next https://github.com/aeternity/terraform-aws-devnet/pull/5
- [x] dev1 https://github.com/aeternity/terraform-aws-devnet/pull/5
- [x] dev2 https://github.com/aeternity/terraform-aws-devnet/pull/5
- [x] integration https://github.com/aeternity/terraform-aws-devnet/pull/5
- [x] main https://github.com/aeternity/terraform-aws-mainnet/pull/10
- [x] main_mon https://github.com/aeternity/terraform-aws-mainnet/pull/10
- [x] api_main https://github.com/aeternity/terraform-aws-mainnet-api/pull/10

**Comment by venimus** [comment]
Done
